version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/workspace/cached
    working_dir: /workspace
  #gerar service mongo
